# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy dev

on:
  push:
    branches: [ develop ]

jobs:
  build_test_deploy:

    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          path: develop

      # Build and test
      - name: Grant execute permission for gradlew
        run: chmod +x develop/gradlew
      - name: Test with Gradle
        run: develop/gradlew -b develop/build.gradle.kts jvmTest jsTest

      # Package
      - name: Package with Gradle
        run: |
          cd develop
          printf "dev $GITHUB_RUN_NUMBER" > 'src/commonMain/resources/version.txt'
          ./gradlew jsWebMinWebpack

      # Deploy to GitHub Pages
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Prepare dev
        run: |
          cp develop/build/web-min-webpack/* gh-pages/dev
          echo '::set-env name=COMMIT_MESSAGE::Deploy dev'
      - name: Push to remote
        run: |
          cd gh-pages
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$COMMIT_MESSAGE" && git push || true
