# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  push:
    branches: [ master ]

jobs:
  build_test_deploy:

    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: master

      # Build, test, package
      - name: Grant execute permission for gradlew
        run: chmod +x master/gradlew
      - name: Test with Gradle
        run: master/gradlew -b master/build.gradle.kts jvmTest
      - name: Package with Gradle
        run: master/gradlew -b master/build.gradle.kts jsWebMinWebpack

      # Semantic Release
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install NPM dependencies
        run: npm ci
      - name: Semantic Release
        run: npx semantic-release

      # Deploy to GitHub Pages
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Prepare production
        run: |
          cp master/build/web-min-webpack/* gh-pages
          echo '::set-env name=COMMIT_MESSAGE::Deploy release'
      - name: Push to remote
        run: |
          cd gh-pages
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$COMMIT_MESSAGE" && git push || true
